 const tileData = [
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/rho-ltw-neck-gaiter',
    'Rho LTW Neck Gaiter',
    'LightWool/Elastane mix neck gaiter keeps the snow out and the warm in. This merino wool/spandex neck gaiter keeps out snow and traps in body heat.',
    '$39.00 ',
    'NA',
    '55 g  / 1.9 oz',
    '13454',
    'Rho LTW Neck Gaiter Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Rho-LTW-Neck-Gaiter-Black.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/rho-ltw-beanie',
    'Rho LTW Beanie',
    'A Wool beanie, featuring a double layered headband and embroidered Bird logo on the side.',
    '$35.00 ',
    'NA',
    '30 g  / 1.1 oz',
    '13456',
    'Rho LTW Beanie Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Rho-LTW-Beanie-Black.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-balaclava-fr-gen-2',
    "Assault Balaclava FR Gen 2 Men's",
    'A flame resistant balaclava that is worn when conducting Direct Action tasks that will provide user protection from flame/incendiaries.',
    '$55.00 ',
    'S-M, L-XL',
    '60 g  / 2.1 oz',
    '27771',
    'Assault Balaclava FR Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Balaclava-FR-Gen-2-Crocodile.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/combat-knee-cap',
    'Combat Knee Cap',
    'Lightweight, anatomically-shaped knee protectors.',
    '$70.00 ',
    'NA',
    '225 g  / 7.9 oz',
    '24873',
    'Combat Knee Cap Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Combat-Knee-Cap-Crocodile.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/rope-glove',
    'Rope Glove',
    'Softshell, leather reinforced glove for short roping and rope rescue work.',
    '$100.00 ',
    'XS, S, M, L, XL, XXL',
    '83.2 g  / 2.9 oz',
    '23848',
    'Rope Glove Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Rope-Glove-Black.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/rho-ltw-neck-gaiter',
    'Rho LTW Neck Gaiter',
    'LightWool/Elastane mix neck gaiter keeps the snow out and the warm in. This merino wool/spandex neck gaiter keeps out snow and traps in body heat.',
    '$39.00 ',
    'NA',
    '55 g  / 1.9 oz',
    '13454',
    'Rho LTW Neck Gaiter Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Rho-LTW-Neck-Gaiter-Crocodile.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/rho-ltw-beanie',
    'Rho LTW Beanie',
    'A Wool beanie, featuring a double layered headband and embroidered Bird logo on the side.',
    '$35.00 ',
    'NA',
    '30 g  / 1.1 oz',
    '13456',
    'Rho LTW Beanie Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Rho-LTW-Beanie-Crocodile.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-balaclava-fr-gen-2',
    "Assault Balaclava FR Gen 2 Men's",
    'A flame resistant balaclava that is worn when conducting Direct Action tasks that will provide user protection from flame/incendiaries.',
    '$55.00 ',
    'S-M, L-XL',
    '60 g  / 2.1 oz',
    '27771',
    'Assault Balaclava FR Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Balaclava-FR-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-balaclava-fr-gen-2',
    "Assault Balaclava FR Gen 2 Men's",
    'A flame resistant balaclava that is worn when conducting Direct Action tasks that will provide user protection from flame/incendiaries.',
    '$55.00 ',
    'S-M, L-XL',
    '60 g  / 2.1 oz',
    '27771',
    'Assault Balaclava FR Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Balaclava-FR-Gen-2-Wolf.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-balaclava-fr-black-gen-2',
    "Assault Balaclava FR Black Gen 2 Men's",
    'A flame resistant balaclava that is worn when conducting Direct Action tasks that will provide user protection from flame/incendiaries.',
    '$55.00 ',
    'S-M, L-XL',
    '50 g  / 1.8 oz',
    '27772',
    'Assault Balaclava FR Black Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Balaclava-FR-Black-Gen-2-Black.jpg'
  ],
  [
    'Apparel Accessories',
    'https://leaf.arcteryx.com/us/en/shop/combat-knee-cap',
    'Combat Knee Cap',
    'Lightweight, anatomically-shaped knee protectors.',
    '$70.00 ',
    'NA',
    '225 g  / 7.9 oz',
    '24873',
    'Combat Knee Cap Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Combat-Knee-Cap-Black.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-zip-neck-sv',
    "Cold WX Zip Neck SV Men's",
    'Cold weather base layer fits next-to-skin, providing warmth plus moisture management.',
    '$166.50 ',
    'XS, S, M, L, XL, XXL',
    '345 g  / 12.2 oz',
    '15391',
    'Cold WX Zip Neck SV Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Zip-Neck-SV-Crocodile.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-ls-shirt-ar---wool',
    "Cold WX LS Shirt AR - Wool Men's",
    'A durable midbase layer long sleeve shirt regulates temperature in cold weather conditions.',
    '$125.00 ',
    'XS, S, M, L, XL, XXL',
    '225 g  / 7.9 oz',
    '25790',
    'Cold WX LS Shirt AR - Wool Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-LS-Shirt-AR---Wool-Black.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-bottom-ar---wool',
    "Cold WX Bottom AR - Wool Men's",
    'A durable midbase layer bottom regulates temperature in cold weather conditions.',
    '$119.00 ',
    'XS, S, M, L, XL, XXL',
    '170 g  / 6 oz',
    '25793',
    'Cold WX Bottom AR - Wool Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Bottom-AR---Wool-Black.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-zip-neck-ar---wool',
    "Cold WX Zip Neck AR - Wool Men's",
    'A durable midbase layer zip neck shirt regulates temperature in cold weather conditions.',
    '$142.00 ',
    'XS, S, M, L, XL, XXL',
    '235 g  / 8.3 oz',
    '25792',
    'Cold WX Zip Neck AR - Wool Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Zip-Neck-AR---Wool-Black.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-boxer-ar---wool',
    "Cold WX Boxer AR - Wool Men's",
    'A durable midbase layer boxer short that regulates temperature in cold weather conditions.',
    '$67.00 ',
    'XS, S, M, L, XL, XXL',
    '100 g  / 3.5 oz',
    '25791',
    'Cold WX Boxer AR - Wool Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Boxer-AR---Wool-Crocodile.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-t-shirt-ar---wool',
    "Cold WX T-Shirt AR - Wool Men's",
    'A durable midbase layer T–shirt regulates temperature in cold weather conditions.',
    '$112.50 ',
    'XS, S, M, L, XL, XXL',
    '180 g  / 6.3 oz',
    '25789',
    'Cold WX T-Shirt AR - Wool Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-T-Shirt-AR---Wool-Crocodile.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-ls-shirt-ar---wool',
    "Cold WX LS Shirt AR - Wool Men's",
    'A durable midbase layer long sleeve shirt regulates temperature in cold weather conditions.',
    '$125.00 ',
    'XS, S, M, L, XL, XXL',
    '225 g  / 7.9 oz',
    '25790',
    'Cold WX LS Shirt AR - Wool Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-LS-Shirt-AR---Wool-Crocodile.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-bottom-ar---wool',
    "Cold WX Bottom AR - Wool Men's",
    'A durable midbase layer bottom regulates temperature in cold weather conditions.',
    '$119.00 ',
    'XS, S, M, L, XL, XXL',
    '170 g  / 6 oz',
    '25793',
    'Cold WX Bottom AR - Wool Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Bottom-AR---Wool-Crocodile.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-boxer-ar---wool',
    "Cold WX Boxer AR - Wool Men's",
    'A durable midbase layer boxer short that regulates temperature in cold weather conditions.',
    '$67.00 ',
    'XS, S, M, L, XL, XXL',
    '100 g  / 3.5 oz',
    '25791',
    'Cold WX Boxer AR - Wool Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Boxer-AR---Wool-Black.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-bottom-sv',
    "Cold WX Bottom SV Men's",
    'Cold weather base layer fits next-to-skin, providing warmth plus moisture management.',
    '$159.00 ',
    'XS, S, M, L, XL, XXL',
    '295 g  / 10.4 oz',
    '15392',
    'Cold WX Bottom SV Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Bottom-SV-Crocodile.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-zip-neck-ar---wool',
    "Cold WX Zip Neck AR - Wool Men's",
    'A durable midbase layer zip neck shirt regulates temperature in cold weather conditions.',
    '$142.00 ',
    'XS, S, M, L, XL, XXL',
    '235 g  / 8.3 oz',
    '25792',
    'Cold WX Zip Neck AR - Wool Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Zip-Neck-AR---Wool-Crocodile.jpg'
  ],
  [
    'Base Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-t-shirt-ar---wool',
    "Cold WX T-Shirt AR - Wool Men's",
    'A durable midbase layer T–shirt regulates temperature in cold weather conditions.',
    '$112.50 ',
    'XS, S, M, L, XL, XXL',
    '180 g  / 6.3 oz',
    '25789',
    'Cold WX T-Shirt AR - Wool Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-T-Shirt-AR---Wool-Black.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-jacket-sv-multicam',
    "Cold WX Jacket SV MultiCam Men's",
    'A windproof cold and wet weather MultiCam® jacket with maximum insulating properties.',
    '$1,149.00 ',
    'S, M, L, XL, XXL',
    '1 kg / 2 lb 4.2 oz',
    '15408',
    'Cold WX Jacket SV MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Jacket-SV-MultiCam-Multicam.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-pant-sv',
    "Cold WX Pant SV Men's",
    'A synthetic insulated cold weather windproof pant.',
    '$749.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '800 g / 1 lb 12.2 oz',
    '22746',
    'Cold WX Pant SV Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Pant-SV-Crocodile.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-jacket-lt-gen-2',
    "Cold WX Jacket LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof jacket.',
    '$405.00 ',
    'XS, S, M, L, XL, XXL',
    '530 g / 1 lb 2.7 oz',
    '23687',
    'Cold WX Jacket LT Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Jacket-LT-Gen-2-Crocodile.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-parka-svx',
    "Cold WX Parka SVX Men's",
    'Exceptionally warm down parka, fully featured for cold weather conditions.',
    '$1,659.00 ',
    'S, M, L, XL, XXL',
    '1.5 kg / 3 lb 3.9 oz',
    '15387',
    'Cold WX Parka SVX Harrier',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Parka-SVX-Harrier.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-pant-lt-gen-2',
    "Cold WX Pant LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof pant.',
    '$359.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '605 g / 1 lb 5.3 oz',
    '23691',
    'Cold WX Pant LT Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Pant-LT-Gen-2-Black.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-hoody-lt-gen-2',
    "Cold WX Hoody LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof hooded jacket.',
    '$422.00 ',
    'XS, S, M, L, XL, XXL',
    '680 g / 1 lb 8 oz',
    '23689',
    'Cold WX Hoody LT Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Hoody-LT-Gen-2-Black.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-hoody-lt-gen-2',
    "Cold WX Hoody LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof hooded jacket.',
    '$422.00 ',
    'XS, S, M, L, XL, XXL',
    '680 g / 1 lb 8 oz',
    '23689',
    'Cold WX Hoody LT Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Hoody-LT-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-pant-sv-multicam',
    "Cold WX Pant SV MultiCam Men's",
    'A synthetic insulated cold weather windproof pant with maximum insulating properties.',
    '$899.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '755 g / 1 lb 10.6 oz',
    '15409',
    'Cold WX Pant SV MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Pant-SV-MultiCam-Multicam.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-jacket-lt-gen-2',
    "Cold WX Jacket LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof jacket.',
    '$405.00 ',
    'XS, S, M, L, XL, XXL',
    '530 g / 1 lb 2.7 oz',
    '23687',
    'Cold WX Jacket LT Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Jacket-LT-Gen-2-Wolf.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-bib-pant-svx',
    "Cold WX Bib Pant SVX Men's",
    'Exceptionally warm down bib pant, fully featured for cold weather conditions.',
    '$1,459.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '990 g / 2 lb 2.9 oz',
    '15388',
    'Cold WX Bib Pant SVX Harrier',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Bib-Pant-SVX-Harrier.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-hoody-lt-gen-2-multicam',
    "Cold WX Hoody LT Gen 2 MultiCam Men's",
    'A synthetic insulated cold weather windproof MultiCam® hooded jacket.',
    '$604.00 ',
    'XS, S, M, L, XL, XXL',
    '620 g / 1 lb 5.9 oz',
    '23690',
    'Cold WX Hoody LT Gen 2 MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Hoody-LT-Gen-2-MultiCam-Multicam.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-jacket-lt-gen-2',
    "Cold WX Jacket LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof jacket.',
    '$405.00 ',
    'XS, S, M, L, XL, XXL',
    '530 g / 1 lb 2.7 oz',
    '23687',
    'Cold WX Jacket LT Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Jacket-LT-Gen-2-Black.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-pant-lt-gen-2-multicam',
    "Cold WX Pant LT Gen 2 MultiCam Men's",
    'A synthetic insulated cold weather windproof pant.',
    '$539.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '570 g / 1 lb 4.1 oz',
    '23692',
    'Cold WX Pant LT Gen 2 MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Pant-LT-Gen-2-MultiCam-Multicam.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-jacket-sv',
    "Cold WX Jacket SV Men's",
    'A synthetic insulated cold weather windproof hooded jacket with maximum insulating properties.',
    '$899.00 ',
    'S, M, L, XL, XXL',
    '1.1 kg / 2 lb 5.6 oz',
    '15383',
    'Cold WX Jacket SV Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Jacket-SV-Crocodile.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-jacket-lt-gen-2-multicam',
    "Cold WX Jacket LT Gen 2 MultiCam Men's",
    'A synthetic insulated cold weather windproof jacket.',
    '$549.00 ',
    'XS, S, M, L, XL, XXL',
    '530 g / 1 lb 2.7 oz',
    '23688',
    'Cold WX Jacket LT Gen 2 MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Jacket-LT-Gen-2-MultiCam-Multicam.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-jacket-sv',
    "Cold WX Jacket SV Men's",
    'A synthetic insulated cold weather windproof hooded jacket with maximum insulating properties.',
    '$899.00 ',
    'S, M, L, XL, XXL',
    '1.1 kg / 2 lb 5.6 oz',
    '15383',
    'Cold WX Jacket SV Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Jacket-SV-Black.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-hoody-lt-gen-2',
    "Cold WX Hoody LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof hooded jacket.',
    '$422.00 ',
    'XS, S, M, L, XL, XXL',
    '680 g / 1 lb 8 oz',
    '23689',
    'Cold WX Hoody LT Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Hoody-LT-Gen-2-Wolf.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-hoody-lt-gen-2',
    "Cold WX Hoody LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof hooded jacket.',
    '$422.00 ',
    'XS, S, M, L, XL, XXL',
    '680 g / 1 lb 8 oz',
    '23689',
    'Cold WX Hoody LT Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Hoody-LT-Gen-2-Crocodile.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-pant-sv',
    "Cold WX Pant SV Men's",
    'A synthetic insulated cold weather windproof pant.',
    '$749.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '800 g / 1 lb 12.2 oz',
    '22746',
    'Cold WX Pant SV Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Pant-SV-Black.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-pant-lt-gen-2',
    "Cold WX Pant LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof pant.',
    '$359.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '605 g / 1 lb 5.3 oz',
    '23691',
    'Cold WX Pant LT Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Pant-LT-Gen-2-Crocodile.jpg'
  ],
  [
    'Cold Weather Insulation',
    'https://leaf.arcteryx.com/us/en/shop/mens/cold-wx-jacket-lt-gen-2',
    "Cold WX Jacket LT Gen 2 Men's",
    'A synthetic insulated cold weather windproof jacket.',
    '$405.00 ',
    'XS, S, M, L, XL, XXL',
    '530 g / 1 lb 2.7 oz',
    '23687',
    'Cold WX Jacket LT Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Cold-WX-Jacket-LT-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/patrol-jacket-ar',
    "Patrol Jacket AR Men's",
    'A general purpose, value added service capable, softshell jacket for law enforcement end-users.',
    '$329.00 ',
    'XS, S, M, L, XL, XXL',
    '550 g / 1 lb 3.4 oz',
    '17660',
    'Patrol Jacket AR Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Patrol-Jacket-AR-Wolf.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-shirt-ar-gen-2',
    "Assault Shirt AR Gen 2 Men's",
    'Full featured, articulated no melt/no drip combat shirt with low profile collar compatible with body armour. Government Sales Only.',
    '$251.00 ',
    'XS, S, M, L, XL, XXL',
    '435 g  / 15.3 oz',
    '23556',
    'Assault Shirt AR Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Shirt-AR-Gen-2-Crocodile.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-pant-lt-multicam',
    "Assault Pant LT MultiCam Men's",
    'A lightno melt/no drip materials based combat pant.',
    '$395.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '500 g / 1 lb 1.6 oz',
    '15708',
    'Assault Pant LT MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pant-LT-MultiCam-Multicam.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/patrol-jacket-ar',
    "Patrol Jacket AR Men's",
    'A general purpose, value added service capable, softshell jacket for law enforcement end-users.',
    '$329.00 ',
    'XS, S, M, L, XL, XXL',
    '550 g / 1 lb 3.4 oz',
    '17660',
    'Patrol Jacket AR Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Patrol-Jacket-AR-Ranger-Green.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/patrol-pant-ar',
    "Patrol Pant AR Men's",
    'A general purpose softshell pant for law enforcement end-users.',
    '$299.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '645 g / 1 lb 6.8 oz',
    '17662',
    'Patrol Pant AR Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Patrol-Pant-AR-Ranger-Green.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-shirt-ar-multicam-gen-2',
    "Assault Shirt AR MultiCam Gen 2 Men's",
    'Full featured, articulated no melt/no drip combat shirt with low profile collar compatible with body armour. Government Sales Only.',
    '$269.00 ',
    'XS, S, M, L, XL, XXL',
    '435 g  / 15.3 oz',
    '23557',
    'Assault Shirt AR MultiCam Gen 2 Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Shirt-AR-MultiCam-Gen-2-Multicam.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-pant-ar-gen-2',
    "Assault Pant AR Gen 2 Men's",
    'Full featured no melt/no drip technical pant suitable for a variety of combat applications. Government Sales Only.',
    '$252.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '717 g / 1 lb 9.3 oz',
    '23558',
    'Assault Pant AR Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pant-AR-Gen-2-Black.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-shirt-lt-multicam',
    "Assault Shirt LT MultiCam Men's",
    'A lightno melt/no drip materials based under body armour combat shirt. Government Sales Only.',
    '$278.00 ',
    'XS, S, M, L, XL, XXL',
    '465 g / 1 lb',
    '17659',
    'Assault Shirt LT MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Shirt-LT-MultiCam-Multicam.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-shirt-ar-gen-2',
    "Assault Shirt AR Gen 2 Men's",
    'Full featured, articulated no melt/no drip combat shirt with low profile collar compatible with body armour. Government Sales Only.',
    '$251.00 ',
    'XS, S, M, L, XL, XXL',
    '435 g  / 15.3 oz',
    '23556',
    'Assault Shirt AR Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Shirt-AR-Gen-2-Black.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/patrol-jacket-ar',
    "Patrol Jacket AR Men's",
    'A general purpose, value added service capable, softshell jacket for law enforcement end-users.',
    '$329.00 ',
    'XS, S, M, L, XL, XXL',
    '550 g / 1 lb 3.4 oz',
    '17660',
    'Patrol Jacket AR Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Patrol-Jacket-AR-Black.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-pant-ar-gen-2',
    "Assault Pant AR Gen 2 Men's",
    'Full featured no melt/no drip technical pant suitable for a variety of combat applications. Government Sales Only.',
    '$252.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '717 g / 1 lb 9.3 oz',
    '23558',
    'Assault Pant AR Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pant-AR-Gen-2-Wolf.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/recce-shirt-lt-multicam',
    "Recce Shirt LT MultiCam Men's",
    'A no melt/no drip materials based combat shirt.',
    '$319.00 ',
    'XS, S, M, L, XL, XXL',
    '330 g  / 11.6 oz',
    '15706',
    'Recce Shirt LT MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Recce-Shirt-LT-MultiCam-Multicam.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-shirt-ar-gen-2',
    "Assault Shirt AR Gen 2 Men's",
    'Full featured, articulated no melt/no drip combat shirt with low profile collar compatible with body armour. Government Sales Only.',
    '$251.00 ',
    'XS, S, M, L, XL, XXL',
    '435 g  / 15.3 oz',
    '23556',
    'Assault Shirt AR Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Shirt-AR-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-pant-ar-gen-2',
    "Assault Pant AR Gen 2 Men's",
    'Full featured no melt/no drip technical pant suitable for a variety of combat applications. Government Sales Only.',
    '$252.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '717 g / 1 lb 9.3 oz',
    '23558',
    'Assault Pant AR Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pant-AR-Gen-2-Crocodile.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-pant-ar-multicam-gen-2',
    "Assault Pant AR MultiCam Gen 2 Men's",
    'Full featured no melt/no drip technical pant suitable for conducting direct action tasks. Government Sales Only.',
    '$359.10 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '717 g / 1 lb 9.3 oz',
    '23559',
    'Assault Pant AR MultiCam Gen 2 Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pant-AR-MultiCam-Gen-2-Multicam.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-shirt-ar-gen-2',
    "Assault Shirt AR Gen 2 Men's",
    'Full featured, articulated no melt/no drip combat shirt with low profile collar compatible with body armour. Government Sales Only.',
    '$251.00 ',
    'XS, S, M, L, XL, XXL',
    '435 g  / 15.3 oz',
    '23556',
    'Assault Shirt AR Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Shirt-AR-Gen-2-Wolf.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-pant-ar-gen-2',
    "Assault Pant AR Gen 2 Men's",
    'Full featured no melt/no drip technical pant suitable for a variety of combat applications. Government Sales Only.',
    '$252.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '717 g / 1 lb 9.3 oz',
    '23558',
    'Assault Pant AR Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pant-AR-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-shirt-sv-multicam',
    "Assault Shirt SV MultiCam Men's",
    'A softshell materials based under body armour combat shirt. Government Sales Only.',
    '$314.00 ',
    'S, M, L, XL, XXL',
    '333 g  / 11.7 oz',
    '19664',
    'Assault Shirt SV MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Shirt-SV-MultiCam-Multicam.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/patrol-pant-ar',
    "Patrol Pant AR Men's",
    'A general purpose softshell pant for law enforcement end-users.',
    '$299.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '645 g / 1 lb 6.8 oz',
    '17662',
    'Patrol Pant AR Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Patrol-Pant-AR-Wolf.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/assault-pant-sv-multicam',
    "Assault Pant SV MultiCam Men's",
    'A softshell materials based combat pant that is worn when conducting Direct Action tasks in cool/cold weather conditions. Government Sales Only.',
    '$675.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT, 2XT',
    '690 g / 1 lb 8.3 oz',
    '17657',
    'Assault Pant SV MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pant-SV-MultiCam-Multicam.jpg'
  ],
  [
    'Combat Uniforms',
    'https://leaf.arcteryx.com/us/en/shop/mens/patrol-pant-ar',
    "Patrol Pant AR Men's",
    'A general purpose softshell pant for law enforcement end-users.',
    '$299.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '645 g / 1 lb 6.8 oz',
    '17662',
    'Patrol Pant AR Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Patrol-Pant-AR-Black.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/blade-20-backpack',
    'Blade 20 Backpack',
    'Minimalist styled pack created to carry daily tools for the digital world',
    '$150.00 ',
    'one size 1.24  kg / 44 oz / 20 L',
    '',
    '16179',
    'Blade 20 Backpack Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Blade-20-Backpack-Black.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/mens/xfunctional-pant-ar-gen-2',
    "xFunctional Pant AR Gen 2 Men's",
    'A durable casual nylon/cotton pant.',
    '$149.00 ',
    '30-32, 32-32, 34-32, 36-32, 38-32, 30-35, 32-35, 34-35, 36-35, 38-35',
    '460 g / 1 lb',
    '22885',
    'xFunctional Pant AR Gen 2 Lahar',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/xFunctional-Pant-AR-Gen-2-Lahar.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/mens/xfunctional-pant-sv',
    "xFunctional Pant SV Men's",
    'A durable casual softshell pant.',
    '$229.00 ',
    '30-32, 32-32, 34-32, 36-32, 38-32, 30-35, 32-35, 34-35, 36-35, 38-35',
    '485 g / 1 lb 1.1 oz',
    '21500',
    'xFunctional Pant SV Rawhide',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/xFunctional-Pant-SV-Rawhide.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/blade-28-backpack',
    'Blade 28 Backpack',
    'Streamlined urban pack with intelligent organization and the capacity for travel.',
    '$160.00 ',
    'one size 1.46  kg / 52 oz / 28 L',
    '',
    '16178',
    'Blade 28 Backpack Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Blade-28-Backpack-Black.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/mens/xfunctional-pant-sv',
    "xFunctional Pant SV Men's",
    'A durable casual softshell pant.',
    '$229.00 ',
    '30-32, 32-32, 34-32, 36-32, 38-32, 30-35, 32-35, 34-35, 36-35, 38-35',
    '485 g / 1 lb 1.1 oz',
    '21500',
    'xFunctional Pant SV Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/xFunctional-Pant-SV-Black.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/mens/aptin-short',
    "Aptin Short Men's",
    'Durable trail running short with four-way stretch.',
    '$89.00 ',
    'XS, S, M, L, XL, XXL',
    '170 g  / 6 oz',
    '18905',
    'Aptin Short Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Aptin-Short-Black.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/courier-bag-15',
    'Courier Bag 15',
    'A messenger style bag capable of carrying a sub-gun platform in a secure and concealed manner.',
    '$279.00 ',
    'NA',
    '970 g / 2 lb 2.2 oz',
    '17669',
    'Courier Bag 15 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Courier-Bag-15-Black.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/blade-6-backpack',
    'Blade 6 Backpack',
    'Smart, streamlined pack designed and organized to manage your daily workflow.',
    '$100.00 ',
    'one size 0.9  kg / 32 oz / 6 L',
    '',
    '16180',
    'Blade 6 Backpack Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Blade-6-Backpack-Black.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/mens/xfunctional-pant-ar-gen-2',
    "xFunctional Pant AR Gen 2 Men's",
    'A durable casual nylon/cotton pant.',
    '$149.00 ',
    '30-32, 32-32, 34-32, 36-32, 38-32, 30-35, 32-35, 34-35, 36-35, 38-35',
    '460 g / 1 lb',
    '22885',
    'xFunctional Pant AR Gen 2 Carbon Steel',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/xFunctional-Pant-AR-Gen-2-Carbon-Steel.jpg'
  ],
  [
    'Cross Functional Product',
    'https://leaf.arcteryx.com/us/en/shop/mens/aptin-short',
    "Aptin Short Men's",
    'Durable trail running short with four-way stretch.',
    '$89.00 ',
    'XS, S, M, L, XL, XXL',
    '170 g  / 6 oz',
    '18905',
    'Aptin Short Cinder',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Aptin-Short-Cinder.jpg'
  ],
  [
    'Load Carriage Equipment',
    'https://leaf.arcteryx.com/us/en/shop/assault-pack-30',
    'Assault Pack 30',
    'Fully padded, single compartment bag.',
    '$399.00 ',
    'one size 1.7  kg / 60 oz / 30 L',
    '',
    '17723',
    'Assault Pack 30 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pack-30-Crocodile.jpg'
  ],
  [
    'Load Carriage Equipment',
    'https://leaf.arcteryx.com/us/en/shop/assault-pack-45',
    'Assault Pack 45',
    'Fully padded, single compartment bag.',
    '$499.00 ',
    'one size 1.895  kg / 67 oz / 45 L',
    '',
    '17725',
    'Assault Pack 45 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pack-45-Black.jpg'
  ],
  [
    'Load Carriage Equipment',
    'https://leaf.arcteryx.com/us/en/shop/assault-pack-30-multicam',
    'Assault Pack 30 Multicam',
    'Fully padded, single compartment bag.',
    '$499.00 ',
    'REG',
    '1.6 kg / 3 lb 9.3 oz',
    '17724',
    'Assault Pack 30 Multicam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pack-30-Multicam-Multicam.jpg'
  ],
  [
    'Load Carriage Equipment',
    'https://leaf.arcteryx.com/us/en/shop/assault-pack-30',
    'Assault Pack 30',
    'Fully padded, single compartment bag.',
    '$399.00 ',
    'one size 1.7  kg / 60 oz / 30 L',
    '',
    '17723',
    'Assault Pack 30 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pack-30-Wolf.jpg'
  ],
  [
    'Load Carriage Equipment',
    'https://leaf.arcteryx.com/us/en/shop/assault-pack-45',
    'Assault Pack 45',
    'Fully padded, single compartment bag.',
    '$499.00 ',
    'one size 1.895  kg / 67 oz / 45 L',
    '',
    '17725',
    'Assault Pack 45 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pack-45-Crocodile.jpg'
  ],
  [
    'Load Carriage Equipment',
    'https://leaf.arcteryx.com/us/en/shop/assault-pack-30',
    'Assault Pack 30',
    'Fully padded, single compartment bag.',
    '$399.00 ',
    'one size 1.7  kg / 60 oz / 30 L',
    '',
    '17723',
    'Assault Pack 30 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pack-30-Black.jpg'
  ],
  [
    'Load Carriage Equipment',
    'https://leaf.arcteryx.com/us/en/shop/assault-pack-45-multicam',
    'Assault Pack 45 Multicam',
    'Fully padded, single compartment bag.',
    '$599.00 ',
    'REG',
    '1.9 kg / 4 lb 1.8 oz',
    '17726',
    'Assault Pack 45 Multicam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pack-45-Multicam-Multicam.jpg'
  ],
  [
    'Load Carriage Equipment',
    'https://leaf.arcteryx.com/us/en/shop/assault-pack-45',
    'Assault Pack 45',
    'Fully padded, single compartment bag.',
    '$499.00 ',
    'one size 1.895  kg / 67 oz / 45 L',
    '',
    '17725',
    'Assault Pack 45 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Assault-Pack-45-Wolf.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-hoody-gen-3',
    "Naga Hoody Gen 3 Men's",
    'A breathable quarter zip fleece mid-layer that can be worn in conjuction with a cold or wet weather layer when conducting special reconnaissance tasks.',
    '$206.50 ',
    'S, M, L, XL, XXL',
    '455 g / 1 lb',
    '25410',
    'Naga Hoody Gen 3 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Hoody-Gen-3-Wolf.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-jacket-gen-2',
    "Atom LT Jacket Gen 2 Men's",
    'A jacket that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket.',
    '$249.00 ',
    'XS, S, M, L, XL, XXL',
    '400 g  / 14.1 oz',
    '21498',
    'Atom LT Jacket Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Jacket-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-hoody-gen-3',
    "Naga Hoody Gen 3 Men's",
    'A breathable quarter zip fleece mid-layer that can be worn in conjuction with a cold or wet weather layer when conducting special reconnaissance tasks.',
    '$206.50 ',
    'S, M, L, XL, XXL',
    '455 g / 1 lb',
    '25410',
    'Naga Hoody Gen 3 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Hoody-Gen-3-Crocodile.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-hoody-gen-2',
    "Atom LT Hoody Gen 2 Men's",
    'A hooded \njacket that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket.',
    '$269.00 ',
    'XS, S, M, L, XL, XXL',
    '455 g / 1 lb',
    '21499',
    'Atom LT Hoody Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Hoody-Gen-2-Crocodile.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-pant-gen-2',
    "Atom LT Pant Gen 2 Men's",
    'A mid layer pant that is worn in either a stand-alone manner or in conjunction with a wet weather protective pant.',
    '$239.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '410 g  / 14.5 oz',
    '21497',
    'Atom LT Pant Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Pant-Gen-2-Crocodile.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-hoody-full-zip-gen-2',
    "Naga Hoody Full Zip Gen 2 Men's",
    'Warm technical mid layer with full zip closure, functional for everyday use.',
    '$232.50 ',
    'S, M, L, XL, XXL',
    '440 g  / 15.5 oz',
    '25411',
    'Naga Hoody Full Zip Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Hoody-Full-Zip-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-jacket-gen-2',
    "Atom LT Jacket Gen 2 Men's",
    'A jacket that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket.',
    '$249.00 ',
    'XS, S, M, L, XL, XXL',
    '400 g  / 14.1 oz',
    '21498',
    'Atom LT Jacket Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Jacket-Gen-2-Crocodile.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-vest-gen-2',
    "Atom LT Vest Gen 2 Men's",
    'A vest that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket .',
    '$189.00 ',
    'XS, S, M, L, XL, XXL',
    '280 g  / 9.9 oz',
    '23861',
    'Atom LT Vest Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Vest-Gen-2-Crocodile.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-hoody-gen-3',
    "Naga Hoody Gen 3 Men's",
    'A breathable quarter zip fleece mid-layer that can be worn in conjuction with a cold or wet weather layer when conducting special reconnaissance tasks.',
    '$206.50 ',
    'S, M, L, XL, XXL',
    '455 g / 1 lb',
    '25410',
    'Naga Hoody Gen 3 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Hoody-Gen-3-Ranger-Green.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-hoody-full-zip-gen-2',
    "Naga Hoody Full Zip Gen 2 Men's",
    'Warm technical mid layer with full zip closure, functional for everyday use.',
    '$232.50 ',
    'S, M, L, XL, XXL',
    '440 g  / 15.5 oz',
    '25411',
    'Naga Hoody Full Zip Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Hoody-Full-Zip-Gen-2-Black.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-pullover-ar-gen-2',
    "Naga Pullover AR Gen 2 Men's",
    'A mid layer that is worn in conjunction with a wet weather protective jacket when conducting Special Reconnaissance tasks.',
    '$255.00 ',
    'S, M, L, XL, XXL',
    '350 g  / 12.3 oz',
    '27776',
    'Naga Pullover AR Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Pullover-AR-Gen-2-Black.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-hoody-gen-2',
    "Atom LT Hoody Gen 2 Men's",
    'A hooded \njacket that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket.',
    '$269.00 ',
    'XS, S, M, L, XL, XXL',
    '455 g / 1 lb',
    '21499',
    'Atom LT Hoody Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Hoody-Gen-2-Black.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-vest-gen-2',
    "Atom LT Vest Gen 2 Men's",
    'A vest that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket .',
    '$189.00 ',
    'XS, S, M, L, XL, XXL',
    '280 g  / 9.9 oz',
    '23861',
    'Atom LT Vest Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Vest-Gen-2-Black.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-hoody-full-zip-gen-2',
    "Naga Hoody Full Zip Gen 2 Men's",
    'Warm technical mid layer with full zip closure, functional for everyday use.',
    '$232.50 ',
    'S, M, L, XL, XXL',
    '440 g  / 15.5 oz',
    '25411',
    'Naga Hoody Full Zip Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Hoody-Full-Zip-Gen-2-Wolf.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-hoody-gen-3',
    "Naga Hoody Gen 3 Men's",
    'A breathable quarter zip fleece mid-layer that can be worn in conjuction with a cold or wet weather layer when conducting special reconnaissance tasks.',
    '$206.50 ',
    'S, M, L, XL, XXL',
    '455 g / 1 lb',
    '25410',
    'Naga Hoody Gen 3 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Hoody-Gen-3-Black.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-pullover-ar-gen-2',
    "Naga Pullover AR Gen 2 Men's",
    'A mid layer that is worn in conjunction with a wet weather protective jacket when conducting Special Reconnaissance tasks.',
    '$255.00 ',
    'S, M, L, XL, XXL',
    '350 g  / 12.3 oz',
    '27776',
    'Naga Pullover AR Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Pullover-AR-Gen-2-Crocodile.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-hoody-gen-2',
    "Atom LT Hoody Gen 2 Men's",
    'A hooded \njacket that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket.',
    '$269.00 ',
    'XS, S, M, L, XL, XXL',
    '455 g / 1 lb',
    '21499',
    'Atom LT Hoody Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Hoody-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-hoody-full-zip-gen-2',
    "Naga Hoody Full Zip Gen 2 Men's",
    'Warm technical mid layer with full zip closure, functional for everyday use.',
    '$232.50 ',
    'S, M, L, XL, XXL',
    '440 g  / 15.5 oz',
    '25411',
    'Naga Hoody Full Zip Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Hoody-Full-Zip-Gen-2-Crocodile.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-jacket-gen-2',
    "Atom LT Jacket Gen 2 Men's",
    'A jacket that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket.',
    '$249.00 ',
    'XS, S, M, L, XL, XXL',
    '400 g  / 14.1 oz',
    '21498',
    'Atom LT Jacket Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Jacket-Gen-2-Wolf.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-hoody-gen-2',
    "Atom LT Hoody Gen 2 Men's",
    'A hooded \njacket that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket.',
    '$269.00 ',
    'XS, S, M, L, XL, XXL',
    '455 g / 1 lb',
    '21499',
    'Atom LT Hoody Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Hoody-Gen-2-Wolf.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-pant-gen-2',
    "Atom LT Pant Gen 2 Men's",
    'A mid layer pant that is worn in either a stand-alone manner or in conjunction with a wet weather protective pant.',
    '$239.00 ',
    'S, M, L, XL, XXL, MT, LT, XLT',
    '410 g  / 14.5 oz',
    '21497',
    'Atom LT Pant Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Pant-Gen-2-Black.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-pullover-ar-gen-2',
    "Naga Pullover AR Gen 2 Men's",
    'A mid layer that is worn in conjunction with a wet weather protective jacket when conducting Special Reconnaissance tasks.',
    '$255.00 ',
    'S, M, L, XL, XXL',
    '350 g  / 12.3 oz',
    '27776',
    'Naga Pullover AR Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Pullover-AR-Gen-2-Wolf.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/naga-pullover-ar-gen-2',
    "Naga Pullover AR Gen 2 Men's",
    'A mid layer that is worn in conjunction with a wet weather protective jacket when conducting Special Reconnaissance tasks.',
    '$255.00 ',
    'S, M, L, XL, XXL',
    '350 g  / 12.3 oz',
    '27776',
    'Naga Pullover AR Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Naga-Pullover-AR-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-jacket-gen-2',
    "Atom LT Jacket Gen 2 Men's",
    'A jacket that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket.',
    '$249.00 ',
    'XS, S, M, L, XL, XXL',
    '400 g  / 14.1 oz',
    '21498',
    'Atom LT Jacket Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Jacket-Gen-2-Black.jpg'
  ],
  [
    'Mid Layer',
    'https://leaf.arcteryx.com/us/en/shop/mens/atom-lt-vest-gen-2',
    "Atom LT Vest Gen 2 Men's",
    'A vest that is worn in either a stand-alone manner or in conjunction with a wet weather protective jacket .',
    '$189.00 ',
    'XS, S, M, L, XL, XXL',
    '280 g  / 9.9 oz',
    '23861',
    'Atom LT Vest Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Atom-LT-Vest-Gen-2-Wolf.jpg'
  ],
  [
    'Personal Protective Equipment',
    'https://leaf.arcteryx.com/us/en/shop/e220-riggers-harness',
    'E220 Riggers Harness',
    'Packaged as an emergency set-up, the Rigger’s Belt comes with a single mesh sling that folds into two leg loops and attaches to the belt to form an emergency harness.',
    '$159.00 ',
    'XS, S, M, L, XL, XXL',
    '245 g  / 8.6 oz',
    '11783',
    'E220 Riggers Harness Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/E220-Riggers-Harness-Black.jpg'
  ],
  [
    'Personal Protective Equipment',
    'https://leaf.arcteryx.com/us/en/shop/e220-riggers-harness',
    'E220 Riggers Harness',
    'Packaged as an emergency set-up, the Rigger’s Belt comes with a single mesh sling that folds into two leg loops and attaches to the belt to form an emergency harness.',
    '$159.00 ',
    'XS, S, M, L, XL, XXL',
    '245 g  / 8.6 oz',
    '11783',
    'E220 Riggers Harness Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/E220-Riggers-Harness-Multicam.jpg'
  ],
  [
    'Personal Protective Equipment',
    'https://leaf.arcteryx.com/us/en/shop/e220-riggers-harness',
    'E220 Riggers Harness',
    'Packaged as an emergency set-up, the Rigger’s Belt comes with a single mesh sling that folds into two leg loops and attaches to the belt to form an emergency harness.',
    '$159.00 ',
    'XS, S, M, L, XL, XXL',
    '245 g  / 8.6 oz',
    '11783',
    'E220 Riggers Harness Coyote',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/E220-Riggers-Harness-Coyote.jpg'
  ],
  [
    'Personal Protective Equipment',
    'https://leaf.arcteryx.com/us/en/shop/mens/ar-395a-harness',
    "AR-395a Harness Men's",
    'Versatile men’s harness for sport, trad, alpine, mixed or ice climbing. AR: All Round',
    '$159.00 ',
    'XS, S, M, L, XL',
    '395 g  / 13.9 oz',
    '15996',
    'AR-395a Harness Black-LEAF',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/AR-395a-Harness-Black-LEAF.jpg'
  ],
  [
    'Station Identification',
    'https://leaf.arcteryx.com/us/en/shop/mens/wbt-t-shirt',
    "WBT T-Shirt Men's",
    'Short-sleeved T-shirt with graphic.',
    '$45.00 ',
    'S, M, L, XL, XXL',
    '155 g  / 5.5 oz',
    '22547',
    'WBT T-Shirt Pilot',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/WBT-T-Shirt-Pilot.jpg'
  ],
  [
    'Station Identification',
    'https://leaf.arcteryx.com/us/en/shop/bac-cap-gen-2',
    'BAC Cap Gen 2',
    'This durable Flexfit® ball cap has a stiff brim/front panel and breathable mesh polyester back.',
    '$35.00 ',
    'NA',
    '72 g  / 2.5 oz',
    '25225',
    'BAC Cap Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/BAC-Cap-Gen-2-Black.jpg'
  ],
  [
    'Station Identification',
    'https://leaf.arcteryx.com/us/en/shop/mens/wbt-t-shirt',
    "WBT T-Shirt Men's",
    'Short-sleeved T-shirt with graphic.',
    '$45.00 ',
    'S, M, L, XL, XXL',
    '155 g  / 5.5 oz',
    '22547',
    'WBT T-Shirt Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/WBT-T-Shirt-Crocodile.jpg'
  ],
  [
    'Station Identification',
    'https://leaf.arcteryx.com/us/en/shop/bac-cap-gen-2',
    'BAC Cap Gen 2',
    'This durable Flexfit® ball cap has a stiff brim/front panel and breathable mesh polyester back.',
    '$35.00 ',
    'NA',
    '72 g  / 2.5 oz',
    '25225',
    'BAC Cap Gen 2 Pilot/Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/BAC-Cap-Gen-2-Pilot-Black.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-jacket-gen-2',
    "Alpha Jacket Gen 2 Men's",
    'Durable waterproof/breathable shell jacket for inclement conditions.',
    '$759.00 ',
    'XS, S, M, L, XL, XXL',
    '575 g / 1 lb 4.3 oz',
    '18863',
    'Alpha Jacket Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Jacket-Gen-2-Wolf.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-pant-gen-2',
    "Alpha LT Pant Gen 2 Men's",
    'Light and packable waterproof/breathable shell pant for inclement conditions.',
    '$499.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '380 g  / 13.4 oz',
    '18865',
    'Alpha LT Pant Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Pant-Gen-2-Crocodile.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-pant-gen-2',
    "Alpha LT Pant Gen 2 Men's",
    'Light and packable waterproof/breathable shell pant for inclement conditions.',
    '$499.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '380 g  / 13.4 oz',
    '18865',
    'Alpha LT Pant Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Pant-Gen-2-Black.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-jacket-gen-2',
    "Alpha Jacket Gen 2 Men's",
    'Durable waterproof/breathable shell jacket for inclement conditions.',
    '$759.00 ',
    'XS, S, M, L, XL, XXL',
    '575 g / 1 lb 4.3 oz',
    '18863',
    'Alpha Jacket Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Jacket-Gen-2-Black.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-pant-gen-2',
    "Alpha Pant Gen 2 Men's",
    'Durable waterproof/breathable shell pant for inclement conditions.',
    '$599.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '510 g / 1 lb 2 oz',
    '19101',
    'Alpha Pant Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Pant-Gen-2-Black.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-pant-gen-2-multicam',
    "Alpha LT Pant Gen 2 MultiCam Men's",
    'Light and packable waterproof/breathable shell pant for inclement conditions.',
    '$619.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '380 g  / 13.4 oz',
    '19950',
    'Alpha LT Pant Gen 2 MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Pant-Gen-2-MultiCam-Multicam.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-jacket-gen-2',
    "Alpha Jacket Gen 2 Men's",
    'Durable waterproof/breathable shell jacket for inclement conditions.',
    '$759.00 ',
    'XS, S, M, L, XL, XXL',
    '575 g / 1 lb 4.3 oz',
    '18863',
    'Alpha Jacket Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Jacket-Gen-2-Crocodile.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-jacket-gen-2-multicam',
    "Alpha Jacket Gen 2 MultiCam Men's",
    'Durable waterproof/breathable shell jacket for inclement conditions.',
    '$969.00 ',
    'XS, S, M, L, XL, XXL',
    '575 g / 1 lb 4.3 oz',
    '19935',
    'Alpha Jacket Gen 2 MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Jacket-Gen-2-MultiCam-Multicam.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-jacket-gen-2',
    "Alpha LT Jacket Gen 2 Men's",
    'Light and packable waterproof/breathable shell jacket for inclement conditions.',
    '$629.00 ',
    'XS, S, M, L, XL, XXL',
    '420 g  / 14.8 oz',
    '18864',
    'Alpha LT Jacket Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Jacket-Gen-2-Crocodile.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-jacket-gen-2',
    "Alpha LT Jacket Gen 2 Men's",
    'Light and packable waterproof/breathable shell jacket for inclement conditions.',
    '$629.00 ',
    'XS, S, M, L, XL, XXL',
    '420 g  / 14.8 oz',
    '18864',
    'Alpha LT Jacket Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Jacket-Gen-2-Black.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-bib-pant-gen-2',
    "Alpha Bib Pant Gen 2 Men's",
    'Durable waterproof/breathable bib shell pant for inclement conditions.',
    '$659.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '620 g / 1 lb 5.9 oz',
    '19103',
    'Alpha Bib Pant Gen 2 Black',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Bib-Pant-Gen-2-Black.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-pant-gen-2-multicam',
    "Alpha Pant Gen 2 MultiCam Men's",
    'Durable waterproof/breathable shell pant for inclement conditions.',
    '$749.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '515 g / 1 lb 2.2 oz',
    '19102',
    'Alpha Pant Gen 2 MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Pant-Gen-2-MultiCam-Multicam.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-bib-pant-gen-2-multicam',
    "Alpha Bib Pant Gen 2 MultiCam Men's",
    'Durable waterproof/breathable bib shell pant for inclement conditions.',
    '$829.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '605 g / 1 lb 5.3 oz',
    '19855',
    'Alpha Bib Pant Gen 2 MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Bib-Pant-Gen-2-MultiCam-Multicam.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-pant-gen-2',
    "Alpha LT Pant Gen 2 Men's",
    'Light and packable waterproof/breathable shell pant for inclement conditions.',
    '$499.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '380 g  / 13.4 oz',
    '18865',
    'Alpha LT Pant Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Pant-Gen-2-Wolf.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-jacket-gen-2',
    "Alpha LT Jacket Gen 2 Men's",
    'Light and packable waterproof/breathable shell jacket for inclement conditions.',
    '$629.00 ',
    'XS, S, M, L, XL, XXL',
    '420 g  / 14.8 oz',
    '18864',
    'Alpha LT Jacket Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Jacket-Gen-2-Wolf.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-pant-gen-2',
    "Alpha LT Pant Gen 2 Men's",
    'Light and packable waterproof/breathable shell pant for inclement conditions.',
    '$499.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '380 g  / 13.4 oz',
    '18865',
    'Alpha LT Pant Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Pant-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-jacket-gen-2-multicam',
    "Alpha LT Jacket Gen 2 MultiCam Men's",
    'Light and packable waterproof/breathable shell jacket for inclement conditions.',
    '$855.00 ',
    'XS, S, M, L, XL, XXL',
    '435 g  / 15.3 oz',
    '19936',
    'Alpha LT Jacket Gen 2 MultiCam Multicam',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Jacket-Gen-2-MultiCam-Multicam.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-pant-gen-2',
    "Alpha Pant Gen 2 Men's",
    'Durable waterproof/breathable shell pant for inclement conditions.',
    '$599.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '510 g / 1 lb 2 oz',
    '19101',
    'Alpha Pant Gen 2 Wolf',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Pant-Gen-2-Wolf.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-jacket-gen-2',
    "Alpha Jacket Gen 2 Men's",
    'Durable waterproof/breathable shell jacket for inclement conditions.',
    '$759.00 ',
    'XS, S, M, L, XL, XXL',
    '575 g / 1 lb 4.3 oz',
    '18863',
    'Alpha Jacket Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Jacket-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-lt-jacket-gen-2',
    "Alpha LT Jacket Gen 2 Men's",
    'Light and packable waterproof/breathable shell jacket for inclement conditions.',
    '$629.00 ',
    'XS, S, M, L, XL, XXL',
    '420 g  / 14.8 oz',
    '18864',
    'Alpha LT Jacket Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-LT-Jacket-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-pant-gen-2',
    "Alpha Pant Gen 2 Men's",
    'Durable waterproof/breathable shell pant for inclement conditions.',
    '$599.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '510 g / 1 lb 2 oz',
    '19101',
    'Alpha Pant Gen 2 Ranger Green',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Pant-Gen-2-Ranger-Green.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-bib-pant-gen-2',
    "Alpha Bib Pant Gen 2 Men's",
    'Durable waterproof/breathable bib shell pant for inclement conditions.',
    '$659.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '620 g / 1 lb 5.9 oz',
    '19103',
    'Alpha Bib Pant Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Bib-Pant-Gen-2-Crocodile.jpg'
  ],
  [
    'Wet Weather Protection',
    'https://leaf.arcteryx.com/us/en/shop/mens/alpha-pant-gen-2',
    "Alpha Pant Gen 2 Men's",
    'Durable waterproof/breathable shell pant for inclement conditions.',
    '$599.00 ',
    'XS, S, M, L, XL, XXL, MS, LS, MT, LT, XLT, 2XT',
    '510 g / 1 lb 2 oz',
    '19101',
    'Alpha Pant Gen 2 Crocodile',
    'https://images-dynamic-arcteryx.imgix.net/S21/1350x1710/Alpha-Pant-Gen-2-Crocodile.jpg'
  ]
]

export default tileData